SELECT * FROM USER_OBJECTS
WHERE OBJECT_TYPE='PROCEDURE';

--MOSTRAR OBJETOS QUE HA CREADO EL USUARIO QUE ESTOY UTILIZANDO.
--SELECT OBJECT_TYPE,COUNT(*) FROM USER_OBJECTS
--GROUP BY object_type

SELECT TEXT FROM USER_SOURCE
WHERE NAME='P1';

