/*select  trigger_name,action_type,trigger_body
from user_triggers; */

--[PARA SABER EL STATUS DEL TRIGER]
/*select OBJECT_NAME,OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE='TRIGGER';
*/

-- [UTILIZADO PARA COMPILAR EL TRIGGER AUNQUE ESTE MALO]
--ALTER TRIGGER TR4_REGION COMPILE;

--[PARA VER LOS ERRORES]
--SELECT * FROM USER_ERRORS;

ALTER TRIGGER TR4_REGION DISABLE;

DESC USER_TRIGGERS;

SELECT TRIGGER_NAME, STATUS
FROM USER_TRIGGERS;
