CREATE OR REPLACE TRIGGER TR2_REGIONS BEFORE
    INSERT OR UPDATE OF region_name OR DELETE ON regions
BEGIN
IF INSERTING THEN 
INSERT INTO LOG_TABLE VALUES ('INSERTANDO', USER);
END IF;
IF UPDATING THEN 
INSERT INTO LOG_TABLE VALUES ('ACTULIZANDO', USER);
END IF;
IF DELETING THEN 
INSERT INTO LOG_TABLE VALUES ('ELIMINANDO', USER);
END IF;
END;